### ISSUE TITLE
AbstractUnit unable to parse prefix-less units (such as "V" or "s")

### ISSUE THREAD

**Issue by mrsell** [unitsofmeasurement/si-units#17]
With version 0.9-SNAPSHOT, the following works:
Unit u = AbstractUnit.parse("mV");

but this results in a ParserException ("javax.measure.format.ParserException: Parse Error"):
Unit u = AbstractUnit.parse("V");

Another example is "ms" (milliseconds) and "s" (seconds).

**Comment by keilw** [comment]
Actually "s" works. Just giving it a try. So far able to reproduce the problem with "V". It's not directly related to SI units but thanks for raising.
