### ISSUE TITLE
Remove unit 'bit'

### ISSUE THREAD

**Issue by michael-o** [unitsofmeasurement/si-units#2]
Bit is neither a base not a derived unit and has never been part of SI. Remove it.

**Comment by keilw** [comment]
You're right regarding SI. There is a task for ISO/IEC 8000: https://github.com/unitsofmeasurement/uom-systems/issues/5 where Bit or Byte are included on top of SI: https://en.wikipedia.org/wiki/ISO/IEC_80000#Units_of_ISO.2FIEC_80000 So we'll relocate both these quantity types and corresponding units to https://github.com/unitsofmeasurement/uom-systems.
Thanks,
Werner
