### ISSUE TITLE
Wrong symbol for degree angle

### ISSUE THREAD

**Issue by toff** [unitsofmeasurement/si-units#24]
The following code:
```
Quantity<Angle> angle = Quantities.getQuantity(Math.PI, SI.RADIAN);
System.out.println(angle.to(NonSI.DEGREE_ANGLE));
```

Display this:
`180.0 [rad?]`

**Comment by keilw** [comment]
Will be addressed with 0.6.3. Please use the SNAPSHOT from JFrog OSS (or build directly from code) in the meantime.
