### ISSUE TITLE
SI.GRAM implementation problem

### ISSUE THREAD

**Issue by cleberecht** [unitsofmeasurement/si-units#4]
I think there is a bug in the SI.GRAM implementation and its conversion.

Using the following code:
```java
Quantity<Mass> m1 = Quantities.getQuantity(1.0, GRAM);
System.out.println(m1.toString());
		
Quantity<Mass> m2 = m1.to(MICRO(GRAM));
System.out.println(m2.toString());
```

i am getting

```
1.0 g
1000000.0 ng
```

The value is correct but the unit is off.

**Comment by keilw** [comment]
Thanks, can you confirm you used SI.GRAM from si-units, not unit-ri? There is a slight overlap we just resolve by modularizing unit systems into a "core" (coming with RI) and others on top like SI, etc. Will test and investigate. It should be µg.

**Comment by keilw** [comment]
There is a special treatment  of KilOGRAM vs. GRAM. Seems for sub-multiples the prefix algorithm gets called once more.So MICRO ends up as NANO and same happens for NANO vs. PETA, etc. Will check it out, it is actually problem of RI and similar implementations, but thanks for raising it here.

**Comment by cleberecht** [comment]
Tanks for the fast answer and you are correct, it is the RI implementation. I am looking forward for the next releases. I really like this project - keep up the good work.

**Comment by keilw** [comment]
Thanks for your positive feedback and support. We're actually just about to publish a "End of Quarter" release as next RC for Public Draft, so we'll try to get a fix into it if possible.

**Comment by keilw** [comment]
Aside from derived quantities like SI.TONNE currently formatted as "Mg" (Megagram;-) the kg vs. g issues are resolved.
