### ISSUE TITLE
Angle degrees

### ISSUE THREAD

**Issue by Jan-Fryblik** [unitsofmeasurement/si-units#57]
Hi,

I am looking for angle unit in degrees with symbol '\u00b0'. Have I overlooked something or is this fundamental unit missing? Thank you for help.

**Comment by keilw** [comment]
No it's there: https://github.com/unitsofmeasurement/si-units/blob/master/units/src/main/java/si/uom/NonSI.java

The symbol is "deg" as per https://en.wikipedia.org/wiki/Degree_(angle), but there are two of them, so we could use the  '\u00b0' for UTF and apply "deg" to the ASCII flavor of SimpleUnitFormat.

**Comment by keilw** [comment]
@Jan-Fryblik has this answered your question and can we close this now?
