### ISSUE TITLE
micro not recognised when using 03BC instead of 00B5

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/si-units#58]
I've noticed that when `micro` is written using the greek character (https://unicode-table.com/en/03BC/) it is not parsed successfully: 
- si parser, unicode, indyria and common format service return `ParserException` with error ```μg not recognized (in μg/ml at index 0)```
- ucum parser throw 'systems.uom.ucum.internal.format.TokenMgrError'  with error: ```Lexical error at line 1, column 1.  Encountered: "\u03bc" (956), after : ""```
- seshat works

Would this be a fix to be done or do you prefer to keep it more strict. Cases like this are frequent in our use cases, when we are processing text extracted from pdfs for example. 

(I've opened the issue here but honestly there are so many projects I was not sure)

**Comment by keilw** [comment]
Which implementation did you use? systems-ucum is the only one with a dedicated UCUMFormat, the others rely on the implementation e.g. SimpleUnitFormat or others.

**Comment by lfoppiano** [comment]
ok I'm using the following implementations: 
- si, commonService, indyria, unicode, defaultFormatService -> `tec.uom.se.format.SimpleUnitFormat`
- seshat -> `tech.uom.seshat.UnitFormat`
- ucumFormatService -> `UCUMFormat`

now looking more closely I'm wondering whether I would need only one exemplary for each (SimpleUnitFormat, UCUMFormat and UnitFormat) or make sense to use them all?

**Comment by keilw** [comment]
UCUM is relatively strict, it may support Unicode for the print output, but parsing happens based on a particular symbol. There we have less freedom. In other cases (seems the case in Seshat, which got a slightly unlucky duplication of the API interface name, legitimate as long as you use explicit package names, but it can be tricky with imports at times) we can see, if aliasing might help.

**Comment by keilw** [comment]
This should be fixed with the underlying implementations of 1.0. Indriya 1.3 and UoM SE 1.0.10.
