### ISSUE TITLE
Missing export package within si-units-java8

### ISSUE THREAD

**Issue by ChristianLutz** [unitsofmeasurement/si-units#64]
After fixing #55 the `Export-Package` is missing for si-units-java8

The current Manifest looks like:

    Manifest-Version: 1.0
    Bundle-License: BSD;link="http://opensource.org/licenses/BSD-3-Clause"
    Bundle-SymbolicName: si-units-java8
    Built-By: werner
    Bnd-LastModified: 1556923657730
    Implementation-Vendor-Id: si.uom
    Specification-Title: International System of Units
    Bundle-DocURL: http://unitsofmeasurement.github.io/si-parent/si-units-
     java8/
    Import-Package: javax.measure;version="[1.0,2)",javax.measure.quantity
     ;version="[1.0,2)",javax.measure.spi;version="[1.0,2)",si.uom.quantit
     y;version="[1.1,2)",tec.uom.se;version="[1.0,2)",tec.uom.se.format;ve
     rsion="[1.0,2)",tec.uom.se.function;version="[1.0,2)",tec.uom.se.quan
     tity;version="[1.0,2)",tec.uom.se.spi;version="[1.0,2)",tec.uom.se.un
     it;version="[1.0,2)"
    Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
    Bundle-Developers: dautelle;email="jean-marie@dautelle.com";name="Jean
     -Marie Dautelle";organization=Airbus;organizationUrl="http://www.airb
     us.com";roles="Architect,Java Developer,Spec Lead";timezone="+1","wer
     ner.keil";email="werner@catmedia.us";name="Werner Keil";organization=
     "Creative Arts & Technologies";organizationUrl="http://www.catmedia.u
     s";roles="Architect,Java Developer,Spec Lead";timezone="+1",otaviojav
     a;email="otaviopolianasantana@gmail.com";name="Otávio Gonçalves de 
     Santana";organization="Individual / SouJava";roles="Expert,Java Devel
     oper,Spec Lead";timezone=-5,desruisseaux;email="martin.desruisseaux@g
     eomatys.com";name="Martin Desruisseaux";organization=Geomatys;organiz
     ationUrl="http://www.geomatys.com";roles="Expert,Java Developer,Jenki
     ns Admin";timezone="+1",duckasteroid;email="christopher.senior@gmail.
     com";name="Chris Senior";organization="Snap-on Inc.";roles="Expert,Ja
     va Developer",eralmas7;email="eralmas7@yahoo.com";name="Almas Shaikh"
     ;organization=Individual;roles="Expert,Java Developer",karen_legrand;
     email="karen.legrand@iem.com";name="Karen Legrand";organization="Inno
     vation Emergency Management (IEM)";organizationUrl="http://www.iem.co
     m";roles=Expert;timezone=-5,rajmahendra;email="rajmahendra@gmail.com"
     ;name="Rajmahendra Hegde";organization="JUG Chennai";roles=Expert
    Bundle-Name: SI Units for Java SE 8
    Bundle-SCM: url="https://github.com/unitsofmeasurement/uom-parent.git/
     si-parent/si-units-java8",connection="scm:git:https://github.com/unit
     sofmeasurement/uom-parent.git/si-parent/si-units-java8",developer-con
     nection="scm:git:https://github.com/unitsofmeasurement/uom-parent.git
     /si-parent/si-units-java8",tag=HEAD
    Implementation-Title: SI Units for Java SE 8
    Bundle-Description: "Units of Measurement SI (Système International d
     'Unités)"
    Implementation-Version: 1.1
    Specification-Vendor: Units of Measurement
    Bundle-ManifestVersion: 2
    Bundle-Vendor: Units of Measurement
    Tool: Bnd-4.2.0.201903051501
    Implementation-Vendor: Units of Measurement contributors
    Bundle-Version: 1.1.0
    Private-Package: si.uom,si.uom.impl,si.uom.impl.quantity
    Created-By: 1.8.0_192 (Oracle Corporation)
    Build-Jdk: 1.8.0_192
    Implementation-URL: http://unitsofmeasurement.github.io/
    Specification-Version: 1.1

**Comment by keilw** [comment]
Strange, there really seems to be a problem with the Felix plugin.

**Comment by keilw** [comment]
I guess this is fixed now.
