### ISSUE TITLE
Test failures on master 

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/si-units#67]
I'm trying to figure out how to use the latest versions and when building the master of this project I get into two main problems: 
1. 	this test tries to convert two double when there is no such method in the indriya master: 

```@Test
	@Ignore("Adjust to PowerOfIntConverter")
	public void testBetweenPrefixes2() {
		UnitConverter conv = KILO(METRE).getConverterTo(GIGA(METRE));
		assertEquals(RationalConverter.of(1d, 1000000d), conv);
	}
```

2. After I've change double to long (I guess that eventually BigInteger should be used instead of double, correct?), I get a lot of more failures: 

```
[ERROR] Failures: 
[ERROR]   AngleTest.testAngleConverter:91 expected:<0.01745329251994329576923690768488613> but was:<0.017453292519943295769236907684886129174041179373241439316730392568668>
[ERROR]   ArithmeticTest.testAdd:51 expected:<16610.38782> but was:<16610.387820000000000000000000000000000000>
[ERROR]   ArithmeticTest.testSubtract2:60 expected:<3339.461218> but was:<3339.461218000000000000000000000000000000>
[ERROR]   ConverterTest.testAngleConverter:50 expected:<0.017453292519943295> but was:<0.017453292519943295769236907684886129174041179373241439316730392568668>
[ERROR]   ConverterTest.testAngleConverterOpposite:58 expected:<57.29577951308232> but was:<57.2957795130823208767981548141051660>
[ERROR]   QuantityPrefixTest.testMicro2:88 expected:<1000000.0> but was:<1000000>
[ERROR]   QuantityPrefixTest.testMilli:77 expected:<1000.0> but was:<1000>
[ERROR]   QuantityPrefixTest.testNano:99 expected:<1.0E9> but was:<1000000000>
[ERROR]   QuantityPrefixTest.testNano2:110 expected:<1.0E9> but was:<1000000000>
```

Should I just ignore tests? Is there any plan to fix them? 

Thanks

**Comment by andi-huber** [comment]
I was investigating the build issues with a fork at [1]. A successful snapshot build (master-eb47a0f257-1) is available at [2]. (Use at your own risk, our make your own fork.)

Not sure how to get this upstream, since I'm building on jdk-8 not jdk-9. (I'm also using jdk-8 builds of Indriya for some of my own projects, as required by some JEE platforms.)

[1] https://github.com/andi-huber/si-units
[2] https://jitpack.io/#andi-huber/si-units

**Comment by lfoppiano** [comment]
Thank you @andi-huber. Do you also use `systems.uom` in your projects?

**Comment by andi-huber** [comment]
I'm afraid, no.

**Comment by keilw** [comment]
While Indriya 2 is built with Java 9, it should not have any minimum JDK other than 8 at runtime, @andi-huber, @lfoppiano Do you have other experiences?

**Comment by andi-huber** [comment]
Interesting, I didn't know. For my part, I've not yet tried any official Indriya 2 builds, so I can't say.

**Comment by lfoppiano** [comment]
@keilw that's correct. I've done a brief test and indriya 2 works indeed with JDK8.

**Comment by keilw** [comment]
And are you getting above problem with JDK 8? The CI build https://circleci.com/gh/unitsofmeasurement/si-units has not failed for over a month, so it is hard to reproduce it.

**Comment by lfoppiano** [comment]
@keilw I've deleted my maven repository and rebuilt it from scratch and it works now. I've seen anyway modification to the tests. I cannot explain how come the CI build works actually... 
I was using the version 2.0-SNAPSHOT

**Comment by keilw** [comment]
This is a side-effect of https://github.com/unitsofmeasurement/indriya/issues/237, it should be working here, but hope we (e.g. @andi-huber ) can address some of the number "creep" especially the many padding zeros feel wrong and annoying, the only alternative could be to use `doubleValue()` but it may reduce precision.
