### ISSUE TITLE
Units wrong on Boltzman Constant

### ISSUE THREAD

**Issue by wnreynoldsWork** [unitsofmeasurement/si-units#68]
public static final Unit<Dimensionless> BOLTZMANN_CONSTANT =  addUnit(new AlternateUnit<Dimensionless>(JOULE.divide(KILOGRAM), "J/K").multiply(BOLTZMANN_CONSTANT_VALUE), "k", true);

should be JOULE.divide(KELVIN).

**Comment by keilw** [comment]
Thanks a lot for spotting this. It must have been a copy/paste problem from another unit like `COULOMB_PER_KILOGRAM`. It's fixed both in master and the 1.x branch. As 2.0 is just about to be released in the next couple of days, thanks for pointing it out before the release. While we may not add any more new elements to the 1.x branch in future, fixing problems in existing units will of course happen and we'll release 1.3 along with 2.0.
