### ISSUE TITLE
NonSI.MILLIMETRE_OF_MERCURY uses approximate value. 

### ISSUE THREAD

**Issue by wnreynoldsWork** [unitsofmeasurement/si-units#73]
Should be MILLIMETRE_OF_MERCURY = PASCAL.multiply(133.322387415)

(see https://en.wikipedia.org/wiki/Millimetre_of_mercury, reference [1]).

currently value is 

 public static final Unit<Pressure> MILLIMETRE_OF_MERCURY = addUnit(PASCAL.multiply(133.322))

**Comment by keilw** [comment]
@wnreynoldsWork It's applied in the latest snapshot of `NonSI`, please check it out and feel free to close yourself if you can.
