### ISSUE TITLE
OSGI package exports are missing in the si-units manifest

### ISSUE THREAD

**Issue by cpmeister** [unitsofmeasurement/si-units#80]
Looks like the osgi package exports are not present in the manifest.
After looking at the pom.xml it seems that you have commented out the section that would add the exports.

**Comment by keilw** [comment]
Guess this may be a similar problem to https://github.com/unitsofmeasurement/uom-lib/pull/65 not what's commented out, because that only was the Felix plugin which we don't use here anymore (and given the problems Felix 5.x has we may not do it that soon)

**Comment by cpmeister** [comment]
The package exports are present in the manifest si-quantity jar but aren't present on the si-units jar. The only difference I can see between the pom file of these two projects is that the si-quantity pom still uses the Felix plugin, si-units has that plugin commented out.

**Comment by keilw** [comment]
That may be a left-over, but unless the bnd-plugin brings the same bugs Felix has from 5.1 we might also drop it there.

**Comment by splatch** [comment]
@keilw What's your take on OSGi metadata? If you tell me what your preference (bnd-maven-plugin, maven-bundle-plugin) and projects I can have a look and prepare working configuration.

**Comment by keilw** [comment]
It's already there in the 2.1-SNAPSHOT, Guess we can close this one.

**Comment by cpmeister** [comment]
Where can I find the snapshot?

**Comment by keilw** [comment]
They're on JFrog/Bintray.

**Comment by NorbertHD** [comment]
Excuse my ignorance, but I can not find the 2.1-SNAPSHOT at [https://bintray.com/unitsofmeasurement](https://bintray.com/unitsofmeasurement).
Can you give the full link please?

**Comment by keilw** [comment]
It's of course in the snapshot repo: <url>https://oss.jfrog.org/artifactory/libs-snapshot</url>
See most of our POMs as well.

**Comment by NorbertHD** [comment]
Thank you, found it: [https://oss.jfrog.org/artifactory/libs-snapshot/tech/units/indriya/2.1-SNAPSHOT/](https://oss.jfrog.org/artifactory/libs-snapshot/tech/units/indriya/2.1-SNAPSHOT/)
