### ISSUE TITLE
Units for MassFlowRate

### ISSUE THREAD

**Issue by samodadela** [unitsofmeasurement/si-units#82]
I was looking for units for MassFlowRate, but all I can find is this:
```
public interface MassFlowRate extends Quantity<MassFlowRate> {
}
```
Am I missing some implementation library for MassFlowRate? 

Also, if you don't mind explaining... I'm a bit confused... is it right to say that MassFlowRate is a Dimension like Area, Force, Length? I'm asking because in the definition above MassFlowRate extends a Quantity.. so it's a Quantity?

**Comment by samodadela** [comment]
Thanks for the explanation and contributing instructions.

As regards MassFlowRate keep/not keep... I already defined a Unit for my use case:
```
public static final Unit<MassFlowRate> MILLIGRAM_PER_SECOND = new ProductUnit<>(MILLI(GRAM).divide(SECOND));
```
I'd keep it, since it helps to interpret what MILLIGRAM_PER_SECOND is - a mass flow rate. Apart from that I do not have other uses for it (yet).

**Comment by keilw** [comment]
Ok, no problem we'll keep it. Of course in your own libraries you are perfectly fine to define `MILLIGRAM_PER_SECOND` or even `POUND_PER_SECOND` for our US friends, but the SI Unit according to http://en.wikipedia.org/wiki/Mass_flow_rate is `KILOGRAM_PER_SECOND` so we'll add that with the upcoming release and also keep this ticket open to track its creation.
