### ISSUE TITLE
Update fundamental constants with 2019 redefinition by BIPM

### ISSUE THREAD

**Issue by PeterC-DLS** [unitsofmeasurement/si-units#83]
See https://www.bipm.org/en/measurement-units/si-defining-constants and the [9th edition of the SI Brochure]( https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf)

**Comment by keilw** [comment]
We have a couple of those, but not every single one I recall.

- [ ] the caesium hyperfine frequency ΔνCs
- [ ] the speed of light in vacuum c
- [ ] the Planck constant h
- [ ] the elementary charge e
- [ ] the Boltzmann constant k
- [ ] the Avogadro constant NA, and
- [ ] the luminous efficacy of a defined visible radiation Kcd

**Comment by PeterC-DLS** [comment]
Elementary charge and speed of light are used too in several places in `SI` and `NonSI` classes.

**Comment by keilw** [comment]
Thanks  @PeterC-DLS, with 2.2 this constant graduated to `SI` marking it for removal in `NonSI` in a future version.
