### ISSUE TITLE
ELECTRON_VOLT unsupported

### ISSUE THREAD

**Issue by ssudekum** [unitsofmeasurement/si-units#87]
https://github.com/unitsofmeasurement/indriya/blob/master/src/main/resources/tech/units/indriya/format/messages.properties#L75

I tried to use `AbstractUnit.parse("MeV")`, and was getting a MeasurementParseException.

I would like to make use of this unit, and  it looks like there is already some level of awareness for the unit within this library.

I wonder if there is some blocker or it is trivial for it to be implemented.

**Comment by keilw** [comment]
This is a non-issue, as `ELECTRON_VOLT` is already declared in the `NonSI `system (holding units that are supported with the SI system but not part of it)
