### ISSUE TITLE
OSGi plugin with si units

### ISSUE THREAD

**Issue by jacqueslorentz** [unitsofmeasurement/si-units#88]
Hello,

I am currently working on a eclipse RAP application and I would like to use the `si.uom.SI` class.
I get the following error: `java.lang.NoClassDefFoundError: si/uom/SI ....`
The application is correctly configured, the si-units bundle is imported.

With the `si.uom.quantity` classes it works well.

Is it related to this commented code?
https://github.com/unitsofmeasurement/si-units/blob/71f6f62b18f214b10902feb48cc2bd8e6307910c/units/pom.xml#L153-L160
In si-quantity the corresponding plugin is not commented:
https://github.com/unitsofmeasurement/si-units/blob/71f6f62b18f214b10902feb48cc2bd8e6307910c/quantity/pom.xml#L29-L41

Thank you very much and have a good day!

**Comment by keilw** [comment]
This has been open for some time, @jacqueslorentz do you still see this problem with the 2.2-SNAPSHOT?

**Comment by keilw** [comment]
I assume, it is resolved with 2.2, otherwise @jacqueslorentz please feel free to reopen or create another one.
